base:
  seed: 42

load_data:
  data_train_path: data/raw/train.csv
  data_test_path: data/raw/test.csv

preprocess_data:
  cols:
    TARGET_COLS: ['Артериальная гипертензия', 'ОНМК', 'Стенокардия, ИБС, инфаркт миокарда', 'Сердечная недостаточность', 'Прочие заболевания сердца']
    ID_COL: 'ID'
    EDU_COL: 'Образование'
    SEX_COL: 'Пол'
    FREQ_COL: 'Частота пасс кур'
    CAT_COLS: [ 'Пол', 'Семья', 'Этнос', 'Национальность', 'Религия', 'Образование', 'Профессия', 'Статус Курения', 'Частота пасс кур', 'Алкоголь', 'Время засыпания', 'Время пробуждения']
    OHE_COLS: [ 'Пол', 'Вы работаете?', 'Выход на пенсию', 'Прекращение работы по болезни', 'Сахарный диабет', 'Гепатит', 'Онкология', 'Хроническое заболевание легких', 'Бронжиальная астма', 'Туберкулез легких ', 'ВИЧ/СПИД', 'Регулярный прим лекарственных средств', 'Травмы за год', 'Переломы','Пассивное курение', 'Сон после обеда', 'Спорт, клубы', 'Религия, клубы']
    REAL_COLS: ['Возраст курения', 'Сигарет в день', 'Возраст алког']

  paths:
    preprocessed_train_data_pkl: data/preprocessed/train_data.pkl 
    preprocessed_target_data_pkl: data/preprocessed/target_data.pkl
    preprocessed_test_data_pkl: data/preprocessed/test_data.pkl

generate_features:
  cols:
    WAKE_UP_TIME_COL: 'Время пробуждения'
    FALL_ASLEEP_COL: 'Время засыпания'
    SLEEP_BEHAVIORS_COL: 'Жаворонок/Сова'
    SLEEP_DURATION_COL: 'Длительность сна (ч.)'

  paths:
    featurized_train_data_pkl: 'data/features/featurized_train_data_pkl'
    featurized_test_data_pkl: 'data/features/featurized_test_data_pkl'


train:
